### ISSUE TITLE
GitHub Task List (Before 8/29/2016 Semester Start)

### ISSUE THREAD

**Issue by RJP43** [ebeshero/newtFire-webDev#67]
- [x] write to GitHub about backups for wikis, issues, milestones, etc. 
- [ ] finish Git GUI tutorial edits
- [x] finish Common Git Commands List for GitShell tutorial
- [x] edit GitShell tutorial introduction paragraphs
- [x] reorganize GitShell tutorial quick reference
- [x] create GitShell Tutorial Section -- GitHub as Social Media 
- [x] create GitShell Tutorial Section -- Troubleshooting
- [x] clean up all other GitShell Tutorial Sections (remove excess pictures,  put in config. info, etc.) 
- [x] Create First Git Shell and GitHub homework Assignment -- include setting up Git, creating a GitHub, reading the DHClass-Hub Welcome files for Troubleshooting and Issues, cloning DHClass-Hub, and student creation of Personal Webpage repositories, and adding one file (picture or anything) to DHClass-Hub sandbox and/or Personal Page Repositories. Also, have each student comment on an issue so they can be added as contributors before adding to sandbox.

**Comment by RJP43** [comment]
- [x] remind to add images from Commons Folder to Site for Git Exercise 1 --- NewIssue_GitEx1.jpg, CommentIssue_GitEx1.jpg, NewRepo_GitEx1.jpg

**Comment by RJP43** [comment]
Do we want to add to our house styles that links get the `target="_blank"` attribute so that they open in a new window... this is useful when sending students away from an assignment or tutorial so they do not loose their place.
