### ISSUE TITLE
Fall Semester Start: General Task List 

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/newtFire-webDev#69]
XML (pressing)
- [ ] Add to Intro XML tutorial, or a second tutorial page, on different approaches to markup in XML to help with transition from recipe encoding to letters. See https://github.com/ebeshero/newtFire-webDev/issues/16

CSS
- [x] Add an `@media print { }` section to the site CSS files which adds page numbers when printing, especially for syllabi (all course sites)
- [ ] Add info on CSS for printing to CSS tutorial
  Helpful leads: https://getflywheel.com/layout/how-to-style-your-website-for-print-with-css/
  https://www.w3.org/TR/CSS2/page.html#page-box
- [ ] Add info on Color Blindness checking and W3C Validation to:
-  CSS and HTML tutorials
- HTML Exercise 2
- Project Guidelines

Tutorial and Exercise Corrections: Review and correct all filed here, prioritizing CDA course. Priority Issues list:
- [ ] Bullet point formatting in Regex Ex 4: https://github.com/ebeshero/newtFire-webDev/issues/63
- [ ] XPath tutorial edit: https://github.com/ebeshero/newtFire-webDev/issues/45
- [x] XSLT Images (new image not currently in XSLT tutorial): https://github.com/ebeshero/newtFire-webDev/issues/65

**Comment by RJP43** [comment]
@ebeshero Do we want to add to our house styles that links get the `target="_blank"` attribute so that when a link is clicked it opens in a new window? This is useful when sending students away from an assignment or tutorial so they do not loose their place. I'm not saying go back and change all the links, but like a here on out kind of thing.

**Comment by RJP43** [comment]
@ebeshero To make all of the regex files consistent and not dependent on their sequence numbering (since this differs from fall to spring) we should change the file name on the text for the RegEx Exercise on Forster Voyage log. Currently, it is `ForsterGeorgComplete-regex2.txt`and  I suggest we remove the `2` at the end of `regex`. Of course, if we do this, we then need to make the edit in the [assignment](http://www.newtfire.org/dh/RegexExerciseVoyage.html) to grab the file by the new file name.

**Comment by RJP43** [comment]
Make edits to streamline the code for [XSLT Exercise 4 CDA](http://newtfire.org/dh/XSLTExercise4.html) and the corresponding [XSLT Exercise 2 CDV](http://newtfire.org/dh/XSLTExercise2_CDV.html) [source XML](http://newtfire.org/dh/NelsonArticle_1888-07-30.xml) ... put paragraph tags around text instead of hard returns.  Edit solution and output files accordingly.

**Comment by RJP43** [comment]
@ebeshero  We might consider adding `\b` and `\B` to the regex tutorial - Learn more [here](http://www.regular-expressions.info/wordboundaries.html)

This may not work in oXygen when matching within XSLT and XQuery. Verify?
