### ISSUE TITLE
Revamping XQuery Assignment Series for CDV

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/newtFire-webDev#84]
@RJP43 Let's list out what we need to do to update existing assignments and materials. @ebeshero I made some edits to this list (starred) to include some discrepancies I found on the syllabus and in one of the other SVG assignments that we should probably also address.

- [x] Revise/update the XQuery / XSLT / KML for mapping assignment
- [x] Plan out a bar-graphing XQuery to SVG assignment
- [x] `*`Rearrange Syllabus for Sigma Tau Delta Conference and gap day on April 3rd (due to repeated KML assignment)
- [x] See https://github.com/ebeshero/newtFire-webDev/issues/61 *(ebb: added file extension info to XQuery tutorial)*
- [x] Check/add normalize-space() to Network Analysis assignment. See https://github.com/ebeshero/DHClass-Hub/issues/176
- [x] Possibly https://github.com/ebeshero/newtFire-webDev/issues/59

**Comment by RJP43** [comment]
# XQuery Exercise 3 - KML assignment
Below is a list of the issues I found with [this assignment](http://newtfire.org/dh/XQueryExercise3.html):

- [x]  The Schism collection has been renamed in eXide database; therefore, in the "Overview of the assignment" section in the first task  `collection('/db/Schism')/*` needs to be changed to collection('/db/churchSchism')/*`  

*ebb: Not an issue! I located the original files for the assignment and created the Schism directory in eXist-db.*
  
- [x]  The files in the collection must have been edited since the assignment was made; therefore, in the "Help with the details" section in the first task the count of location distinct values is now 44 **not** 46. 
*ebb: Again, non-issue since I've restored the original directory*

 - [x] Also, the line feed character: `&#10;` is not returning a line return after each location in XQuery. This is a problem because the GPS Visualizer tool requires each location to be on a separate line or in a tabular format. My work around for this was to create a new document to be saved in the database using the `declare variable $ThisFileContent:` that we taught them before spring break and then opening the file in XQuery and copying the list from there. 
*ebb: Noted on assignment, if you use string-join() for this, you need to wrap the FLWOR and its output in the function. . . will model this interesting weirdness in class*

 - [x]  One thing to notice here is that this is messy data there are repeats due to whitespace and alt. spellings. We could ask that they clean up the data before putting into the Visualizer (since that is what one would do if this was a project file, but I am going to run with it for now and see the output. One glaring error that comes across and should prob. be removed before putting in the Visualizer is this entry: `those in Quincy, Ill.` to fix this I simply removed the `those in` before putting the list into the Visualizer. **Note: the Bing API key still works!**



- [x] In bullet point 2 under task number 4 in the "Help with the details" section we tell the students "to define a variable that will look up for *each* of the location names in that distinct-values list (using that range variable still), the very first paragraph (coded as `<p>` in the XML files of the Schism collection)" but the problem here is that the current files in the collection do not use the`< p>` element. Instead, telling students to grab each location's surrounding or parent  `<sec>` gets output that puts the place in context with the text it appears in or we could have them output the file the place is mentioned in using base-uri.  
*ebb: On their new files the `<sec>` wasn't returning much that was useful contextually, which motivated me to hunt for the original files. We're now working with paragraphs, only this time I'm asking them to locate the **longest** paragraph to output with each place in the project KML.*

- [x] In bullet point 3 under task number 4 in the "Help with the details" section we should clarify students should open the sample KML file in oXygen since two options come up (the other being the compressed kml mentioned in the assignment previously).  

- [x] This error pops up when you run the XSLT `SXXP0005: The source document is in namespace http://www.opengis.net/kml/2.2, but none of the template rules match elements in this namespace (Use --suppressXsltNamespaceCheck:on to avoid this warning)` and then if you look in the output none of the descriptions from the XQuery generated KML file have transferred over to the new KML file (that is to be imported into Google Maps). I resolved this by changing the namespace in the GPS Visualizer KML file to match the namespace provided on the assignment and used in the XSLT (http://earth.google.com/kml/2.2). This worked and the descriptions were brought over from the other file into the new file. 
*ebb: I discover that Bing API is actually NOW using the correct namespace for KML, so we don't need all the hullaballoo about inconsistent KML namespaces on this assignment any more. Yay! Editing those out.*
  
I then went ahead and looked over the [other version of this assignment](http://newtfire.org/dh/XQueryExercise-KML.html) (which judging by the dates in the SSI was updated more recently) and I am not seeing many differences (especially any edits that would have fixed the issues I mention above). It looks like the only real difference between those files is the main heading and the image that appears on the alternate version but not on the version titled XQuery Exercise 3.

*ebb: I'm deleting the old file and replacing as XQueryExercise3*

**Comment by RJP43** [comment]
@ebeshero  notes from us re-working the schedule this morning:

3/13 - XQuery 3 (KML)
3/15 - SVG 1 (draw by hand)
3/17 - SVG XQuery Timeline Part 1
3/20 - SVG XQuery Timeline Part 2
3/22 - **NEW ASSIGNMENT** on SVG XQuery  Bar, Line, or Pie Graph ([Georg Forster Stacked Bar Graph Assignment](http://newtfire.org/dh/SVGExercise2.html) - rewrite, rework, new collection ?) We are thinking we should do a GraveYard Graph!
3/24 - Cytoscape Install and start on XQuery Network Ex Part 1
3/27 - Cytoscape XQuery Network Ex Part 1
3/29 - Cytoscape XQuery Network Ex Part 2
3/31 - **DR. B. away for STD Conference** - Project Work Day (possibly data viz work day)
4/3 - Javascript Exercise 1
4/5 - Javascript Exercise 2
4/7 - **NEW ASSIGNMENT** on JavaScript with XQuery SVG
4/10-4/17 - Project Development Days (4/14 Invited to Oakland for Group Presentations)
4/19-4/21 - Original Presentation Days
4/27 - Projects DUE!

**Comment by ebeshero** [comment]
Syllabus dates are revamped.

**Comment by RJP43** [comment]
# Comments on NEW [SVG Exercise 4](http://newtfire.org/dh/SVGExercise4_CDV.html)
  
- [x] "specifically for a group of 142 burials in Section A of the graveyard" AND "we are able to look up and plot information about each family represented in section A" in the first paragraph -- Actually, I believe it is Section I. Can you verify this @jonhoranic ? If it is Section I, we will need to re-output the [example SVG](http://dxcvm05.psc.edu:8080/exist/rest/db/classExampleQueries/graveyardTester.svg) with the corrected section value in the title.

- [x] I assume the white portion of the stacked bar graph represents unavailable information... we should include that in the Legend on the [example SVG](http://dxcvm05.psc.edu:8080/exist/rest/db/classExampleQueries/graveyardTester.svg)

**Comment by ebeshero** [comment]
Made new assignments, and made all revisions to XQuery 2 and Network Analysis Ex 1. I believe my work is done here.
